### ISSUE TITLE
Game and Listen Server crashes for someone who doesn't have the plugin files in their addons folder.

### ISSUE THREAD

**Issue by WeegeeThyme** [KernCore91/-SC-Cry-of-Fear-Weapons-Project#1]
No matter how hard I try I have done so much troubleshooting and nitpicking what could be the culprit and fixing it via verifying the game cache after deleting the file or other means. Meaning, removing metamod-p to player models and maps in the addons folder, but to no avail. The insurgency weapons plugin works fine, but just not this plugin as everything is fine when it comes to installing it and starting a listen server but when I get someone to join when they have a clean install of sven it just freezes my game when it downloads the sound cache of the map I was testing on (-sp_campaign_start) and then just closes the game with no further info.

**Comment by KernCore91** [comment]
I found out that there is a crash related to the v_actions script.  
The game used to accept registering the weapon before with the name `v_action`.  
I changed this to `weapon_cofaction` now, seems to have worked on my end.

**Comment by WeegeeThyme** [comment]
Had trouble wrapping my head around what the solution is that you found unless you're willing to just make an update of the files on GitHub of the fix. I will close the issue if the problem resolves.

**Comment by WeegeeThyme** [comment]
Now this is resolved (I think.) but now the edit made the plugin stop working.
